title: Sentry Documentation
description: >-
  Learn how to use Sentry, configure Sentry clients, and contribute to the open
  source project on GitHub
meta_image: default.jpg
baseurl: ""
url: "https://docs.sentry.io"
twitter_username: getsentry
github_username:  getsentry

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-assets
  - jekyll-extlinks

timezone: America/Los_Angeles

source: src

assets:
  autoprefixer:
    browsers:
      - 'last 2 versions'
      - 'ie > 9'

extlinks:
  attributes: {rel: nofollow}
  rel_exclude: ['sentry.io', 'getsentry.com']
